apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sre-microservices
data:
  DATABASE_URL: "postgresql://sre_admin:super_secret_sre_password_2026@postgres:5432/microservices_db"
  POSTGRES_USER: "sre_admin"
  POSTGRES_DB: "microservices_db"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  PRODUCT_SERVICE_URL: "http://product-service:8000"
  ALLOWED_ORIGINS: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: sre-microservices
type: Opaque
stringData:
  POSTGRES_PASSWORD: "super_secret_sre_password_2026"
  GRAFANA_PASSWORD: "admin"
